### ISSUE TITLE
feature: Add country data to each node

### ISSUE THREAD

**Issue by mohamedmansour** [ethereum/node-crawler#1]
Since this is P2P, we have information on each node, would be nice visualization if we convert ip address to a country location, and add that to the database. We do not want to store lat/long for privacy purposes.

**Nice visualizations could come from this:**

- World map (countries)
- Drill down on countries for advanced filtering

**Technical Details:**
The `nodestable` has an IP column, we need to convert that IP to a country string. So we need to figure out how to do that, once that is done, we can create a `country` column in the `nodes` table, and append the dashboard query in `api.go` with the new top countries query. Then in the frontend, we can start with a bar graph with the countries. And add drilldown to that as well. The frontend is pretty straight forward since we can copy the same thing that clients did.

**Comment by mohamedmansour** [comment]
We can use this https://github.com/oschwald/geoip2-golang

**Comment by b-m-f** [comment]
Hi @mohamedmansour ,

this is sth I wanted to implement myself recently.

You can assign me on this for now. I will be trying to get everything up and running and start work this week.

**Comment by mohamedmansour** [comment]
@b-m-f great, we already have the geoip stuff in the crawler, we just need to include it in the api and render it in the web app.

**Comment by b-m-f** [comment]
Alright. Thanks for the info.

I'll try to wire it up tomorrow

**Comment by mohamedmansour** [comment]
Super cool thank you!
