### ISSUE TITLE
ux: Add service worker for client caching

### ISSUE THREAD

**Issue by mohamedmansour** [ethereum/node-crawler#11]
Always good to place a service worker to cache fetch calls and resources, so save costs on server side for a static website that invalidates every 30 minutes

**Comment by MariusVanDerWijden** [comment]
https://github.com/ethereum/node-crawler/commit/0f1b1375b117f854f9232e9f0059fd367746fd06 Implements caching

**Comment by mohamedmansour** [comment]
Decided against this and use content cache instead on api header. Easier to manage that way
