### ISSUE TITLE
no such table: nodes

### ISSUE THREAD

**Issue by ucwong** [ethereum/node-crawler#12]
```
./node-crawler-backend 
Error reading nodes: no such table: nodes
```

**Comment by MariusVanDerWijden** [comment]
Yep, you need to have a `nodetable` file created by the crawler

**Comment by MariusVanDerWijden** [comment]
Crawler is here: https://github.com/ethereum/go-ethereum/pull/22664

**Comment by mohamedmansour** [comment]
We have added docker files that showcase how to run this from scratch, maybe we can update the readme to reflect that @taxmeifyoucan

**Comment by mohamedmansour** [comment]
Closing this issue since the docs are now updated in the README for running docker setup.
