### ISSUE TITLE
Site currently printing "No data available" responses

### ISSUE THREAD

**Issue by BenedettiLucca** [ethereum/node-crawler#32]
No idea if this project is still under active development but i was trying to look at some node stats and got this. 

![image](https://user-images.githubusercontent.com/108427035/191873708-03f761d0-3259-419a-8a9a-a336257986de.png)

**Comment by b-m-f** [comment]
https://crawler.ethereum.org/v1/dashboard responds with 
```
{"clients":null,"languages":null,"operatingSystems":null,"versions":null}
```

I faced the same issue locally when the DBs were not linked correctly.

**Comment by mohamedmansour** [comment]
@taxmeifyoucan  can you see if the DB is missing?

**Comment by taxmeifyoucan** [comment]
There is a bug because of which new crawled data won't make it to the database and when API throws away old nodes after 24h, db is wiped
