### ISSUE TITLE
Handle beacon nodes

### ISSUE THREAD

**Issue by b-m-f** [ethereum/node-crawler#36]
I have come across https://migalabs.es/beaconnodes and https://www.nodewatch.io/ that cover similar functionality.

Should these be the GOTO pages or shold https://crawler.ethereum.org/ become the preferred site to monitor? @mohamedmansour

**Comment by mohamedmansour** [comment]
@MariusVanDerWijden @taxmeifyoucan  should we do it?

**Comment by taxmeifyoucan** [comment]
Crawling beacon nodes requires using p2p protocol of the consensus layer, this crawler should stay focused on execution nodes. There are aggregators of various sources like https://clientdiversity.org/
