### ISSUE TITLE
api: Add caching to dashboard API call

### ISSUE THREAD

**Issue by mohamedmansour** [ethereum/node-crawler#8]
Since the API doesn't do any dynamic processing, it would be safe to add caching layer to minimize the amount of times it hits the database. Perhaps a 10 min TTL (whatever the parameter we set)

**Comment by mohamedmansour** [comment]
We could add in memory cache in the GO API
or
We could add Cloudflare to cache entire site.

**Comment by MariusVanDerWijden** [comment]
0f1b137 Implements caching
